config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :articles
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    
    validates :title, presence: true,
                      length: {minimum: 3, maximum: 50}
    
    validates :description, presence: true,
                            length: {minimum: 5, maximum: 150}
                            
    validates :user_id, presence: true
    
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    has_secure_password #Harry le met après validates email... plus joli là
    
    before_save {self.email.downcase!}
    
    validates :username, presence: true,
                         length: {minimum: 3, maximum: 20},
                         uniqueness: { case_sensitive: false }
                         
    VALID_EMAIL_REGEX = /.+\@.+\..+/i
    
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end
    
    def require_user
        if !logged_in?
            flash[:danger] = "Oh tu fais quoi là ? T'es pas connecté !"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index
        @articles = Article.paginate(:page => params[:page], :per_page => 5)
    end
    def new
        
        @article = Article.new
        
    end
    
    def edit
    end
    
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article bien créé !"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end
    
    
    def update
        if @article.update(article_params)
            flash[:success] = "Article bien modifié"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end
    
    def show
    end
    
    def destroy
        @article.destroy
        flash[:success] = "Article supprimé !"
        
        redirect_to articles_path
    end
    
    
    private
    def article_params
       params.require(:article).permit(:title, :description) 
    end
    
    def set_article
        @article = Article.find(params[:id])
    end
    
    def require_same_user
       if current_user != @article.user && current_user.admin? == false
          flash[:danger] = "C'est pas ton article, tu fous quoi ?"
          redirect_to root_path
       end
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def home
       redirect_to articles_path if logged_in?
   end
   
   def about
       
   end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
       
   end
   
   def create
       user = User.find_by(email: params[:session][:email].downcase)
       if user && user.authenticate(params[:session][:password])
           flash[:success] = "Connexion réalisée, bienvenue bg !"
           session[:user_id] = user.id
           redirect_to user_path(user)
       else
           flash.now[:danger] = "Identifiants incorrects, t'es recalé"
           render 'new'
       end
   end
   
   def destroy
       session[:user_id] = nil
       flash[:success] = "Déconnecté, à bientôt j'espère !"
       redirect_to root_path
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :set_user, only: [:show, :edit, :update, :destroy]
   before_action :require_same_user, only: [:edit, :update, :destroy]
   before_action :require_admin, only: [:destroy]
   
   def index
      @users = User.paginate(:page => params[:page], :per_page => 5)
   end
   
   def new
       @user = User.new
   end
   
   def create
       @user = User.new(user_params)
       if @user.save
           session[:user_id] = @user.id
           flash[:success] = "Compte de #{@user.username} bien créé !"
           redirect_to user_path(@user)
       else
           render 'new'
       end
   end
   
   def edit
   end
   
   def destroy
      @user.destroy
      flash[:success] = "Compte et ses articles détruits !"
      redirect_to users_path
   end
   
   def update
      if @user.update(user_params)
         flash[:success] = "Mise à jour de compte effectuée"
         redirect_to articles_path
      else
         render 'edit'
      end
   end
   
   def show
      @user_articles = @user.articles.paginate(:page => params[:page], :per_page => 5)
   end
   
   private
   
   def user_params
       params.require(:user).permit(:username, :email, :password)
   end
   
   def set_user
      @user = User.find(params[:id])
   end
   
   def require_same_user
      if current_user != @user && !current_user.admin?
         flash[:danger] = "Oh tu fais quoi ? C'est pas ton compte alors bouge de là !"
         redirect_to root_path
      end
   end
   
   def require_admin
      if logged_in? && !current_user.admin?
         flash[:danger] = "Pouvoirs insuffisants"
         redirect_to users_path
      end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(user, options = { size: 200})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
    
end

app/views/articles/_form.html.erb
<%= render 'shared/validerrors', obj: @article %>

<div class="row">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%=  f.label :title%>
            </div>
            <div class="col-sm-6">
                <%=  f.text_field :title, class: "form-control", placeholder: "Titre"%>
            </div>
        </div>
    
        
        
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%=  f.label :description%>
            </div>
            <div class="col-sm-6">
                <%=  f.text_area :description, rows: 10, class: "form-control", placeholder: "Description"%>
            </div>
        </div>
        
        
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: "btn btn-default"%>
            </div>
        </div>
        
    
    <% end %>
</div>

<div class="col-sm-offset-2">
    <%= link_to "Retour aux articles", articles_path %>
</div>

app/views/articles/_liste.html.erb
<table class="table"> <!--solution temporaire, parce que col-xs du div2 ne fonctionne pas -->

        <thead>
            <tr>
                <th>Titre</th>
                <th>Descriptions</th>
                <th>Informations</th>
                <th>Actions</th>
                <th></th>
            </tr>
        </thead>
        
        <% obj.each do |article| %>
            <tr>
                <td><%= link_to article.title, article_path(article) %></td>
                <td><%= truncate(article.description, length:60) %></td>
                <td><small> Created by <b><%= article.user.username if article.user%></b> <%= time_ago_in_words(article.created_at) %> ago, 
                                and last modified <%= time_ago_in_words(article.updated_at) %> ago </small></td> <!-- solution temporaire inclusion des articles antérieurs au modèle user -->
                
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <td><%= link_to "Éditer", edit_article_path(article), class: "btn btn-xs btn-primary" %></td>
                    <td><%= link_to "Supprimer", article_path(article), method: :delete, class: "btn btn-xs btn-danger" %></td>
                <% else %>
                    <td></td>
                    <td></td>
                <% end %>
            </tr>
        <% end %>
            
</table>

app/views/articles/edit.html.erb
<h1 class="col-sm-offset-2">Edition d'article...</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>Liste des articles ALPHA !</h1>
        
        <p><%= link_to "Créer un nouvel article", new_article_path %> </p>
        
        
        <div align="center">
            <%= will_paginate @articles %>
        </div>
        
        <%= render 'liste', obj: @articles %>
        
        <div align="center">
            <%= will_paginate @articles %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="col-sm-offset-2">Création d'un article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
    <div class="col-xs-offset-2 col-xs-10">
        <h2><%= @article.title %></h2>
        
        <div class="well col-xs-6">
            <%= @article.description %>
            
            <% if @article.user %>
                <div align="right">
                    Article par <%= gravatar_for @article.user, size: 35 %> <%= link_to @article.user.username, user_path(@article.user) %>
                </div>
            <% end %>
            <div class="article-actions">
                
                <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                    <%= link_to "Éditer l'article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
                    <%= link_to "Supprimer l'article", article_path(@article), method: :delete, class: "btn btn-xs btn-danger" %>
                <% end %>
                <%= link_to "Retour aux articles", articles_path, class: "btn btn-xs btn-success" %>
            </div>
        </div>
    </div>
    
</div>

app/views/layouts/_flash.html.erb
<div class="row">
   <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg|  %>
         <div class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash-#{name}" if msg.is_a?(String) %>
         </div>
      <% end %>
   </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer>
        <small>
            Alpha blog from <%= link_to "RHC", "https://railsheroescourse.fr"%> Copyright by Quesyrt
        </small>
        <nav>
            <ul>
                <li><%= link_to 'A propos', about_path%></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#" id="logo">Alpha Blog</a> -->
      <%= link_to "Alpha-Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "A propos", about_path  %></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Contributeurs", users_path %></li>
        
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Nouvel article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        
        <% if logged_in? %>
          <li><%= link_to "Déconnexion", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profil 
            <%= "(admin)" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Mes articles", user_path(current_user) %></li>
              <li><%= link_to "Mes infos", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        
        
        <% else %>
          <li><%= link_to "Connexion", login_path %></li>
          <li><%= link_to "S'inscrire", signup_path %></li>
        <% end %>
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About ALPHA...</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'About',  about_path %>

app/views/pages/home.html.erb
<div class="container center">
    <div class="jumbotron">
        <h1>Alpha Blog</h1>
        <p>Des articles de haute qualité pour les esprits les plus tenaces.</p>
        <p><%= link_to "Rejoins-nous !", signup_path, class: "btn btn-primary btn-lg" %></p>
    </div>
</div>

app/views/shared/_validerrors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-6 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        Présence de <%= pluralize(obj.errors.count, "erreur") %> :
                    </h2>
                    <div class="panel-body">
                        <ul>
                             <% obj.errors.full_messages.each do |msg| %>
                                 <li><%= msg %></li>
                             <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/validerrors', obj: @user %>

<div class="row">
    <div class="col-sm-offset-2">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%=  f.label :username%>
            </div>
            <div class="col-sm-6">
                <%=  f.text_field :username, class: "form-control", placeholder: "Identifiant"%>
            </div>
        </div>
    
        
        
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%=  f.label :email%>
            </div>
            <div class="col-sm-6">
                <%=  f.text_field :email, class: "form-control", placeholder: "Email"%>
            </div>
        </div>
        
        
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%=  f.label :password%>
            </div>
            <div class="col-sm-6">
                <%=  f.password_field :password, class: "form-control", placeholder: "Mot de passe"%>
            </div>
        </div>
        
        
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit(@user.new_record? ? "Inscription" : "Enregistrer les modifications", class: "btn btn-default")%>
            </div>
        </div>
        
    
    <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edition de compte</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align = 'center'>Nos contributeurs</h1>


<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div align="center">
            <%= will_paginate @articles %>
        </div>
        <ul class="list-group">
            <%= @users.each do |user| %>
                
                
                <div class="panel panel-default">
                  <div class="panel-heading">
                        <h3 class="panel-title">
                            <%= gravatar_for user, size: 25 %>
                            <%= link_to user.username, user_path(user) %>
                            <% if logged_in? && current_user.admin? %>
                                <%= link_to "Supprimer l'utilisateur",
                                    user_path(user),
                                    method: :delete,
                                    data: {confirm: "Détruire compte et articles de l'utilisateur #{user.username} ?"},
                                    class: "btn btn-xs btn-danger"
                                %>
                            <% end %>
                        </h3>
                  </div>
                  
                  <div class="panel-body">
                        <%= pluralize(user.articles.count, "article") if user.articles %>
                        
                  </div>
                </div>
            <% end %>
        </ul>
    </div>
</div>

app/views/users/new.html.erb
<h1 align='center'>Création de compte</h1><br />

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Contributeur <b><%= @user.username %></b></h1>

<div class = 'row'>
    <div class = 'col-md-6 col-md-offset-3 center'>
        <%= gravatar_for @user, size: 120 %>
    </div>
</div>

<h3 align = 'center'>Articles de <%= @user.username %></h3>

<div class = 'row'>
    <div class = 'col-md-6 col-md-offset-3 center'>
        <%= will_paginate @user_articles %>
        <%= render 'articles/liste', obj: @user_articles %>
        <%= will_paginate @user_articles %>
    </div>
</div>